name: build

on:
  push:
    branches:
    - master
    - 'renovate/**'
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Install curl and curl-dev
        run: |
          sudo apt-get install -y curl
          sudo apt-get install -y libcurl4-gnutls-dev

      - name: Build with Gradle
        uses: eskatos/gradle-command-action@v3
        with:
          gradle-version: current
          arguments: build
